// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VtbGenericVga.h for the primary calling header

#ifndef VERILATED_VTBGENERICVGA___024ROOT_H_
#define VERILATED_VTBGENERICVGA___024ROOT_H_  // guard

#include "verilated.h"


class VtbGenericVga__Syms;

class alignas(VL_CACHE_LINE_BYTES) VtbGenericVga___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clock50MHz,0,0);
        VL_IN8(resetn,0,0);
        VL_OUT8(hSync,0,0);
        VL_OUT8(vSync,0,0);
        VL_OUT8(visible,0,0);
        VL_OUT8(red,7,0);
        VL_OUT8(green,7,0);
        VL_OUT8(blue,7,0);
        CData/*0:0*/ tbGenericVga__DOT__hSyncReg;
        CData/*0:0*/ tbGenericVga__DOT__vSyncReg;
        CData/*0:0*/ tbGenericVga__DOT__visibleReg;
        CData/*7:0*/ tbGenericVga__DOT__dut__DOT__final_r_comb;
        CData/*7:0*/ tbGenericVga__DOT__dut__DOT__final_g_comb;
        CData/*7:0*/ tbGenericVga__DOT__dut__DOT__final_b_comb;
        CData/*0:0*/ tbGenericVga__DOT__dut__DOT__unnamedblk2__DOT__nearest_hit;
        CData/*0:0*/ tbGenericVga__DOT__dut__DOT__unnamedblk2__DOT__hit_tmp;
        CData/*0:0*/ tbGenericVga__DOT__dut__DOT__unnamedblk2__DOT__in_shadow;
        CData/*0:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__10__hit;
        CData/*0:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__41__hit;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clock50MHz__0;
        CData/*0:0*/ __VactContinue;
        VL_OUT16(xOrd,9,0);
        VL_OUT16(yOrd,9,0);
        SData/*9:0*/ tbGenericVga__DOT__xReg;
        SData/*9:0*/ tbGenericVga__DOT__yReg;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT__unnamedblk2__DOT__nearest_t;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT__unnamedblk2__DOT__nearest_idx;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT__unnamedblk2__DOT__t_tmp;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT__unnamedblk2__DOT__hit_x;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT__unnamedblk2__DOT__hit_y;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT__unnamedblk2__DOT__hit_z;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT__unnamedblk2__DOT__norm_x;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT__unnamedblk2__DOT__norm_y;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT__unnamedblk2__DOT__norm_z;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT__unnamedblk2__DOT__norm_raw_x;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT__unnamedblk2__DOT__norm_raw_y;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT__unnamedblk2__DOT__norm_raw_z;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT__unnamedblk2__DOT__to_light_x;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT__unnamedblk2__DOT__to_light_y;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT__unnamedblk2__DOT__to_light_z;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT__unnamedblk2__DOT__ldir_x;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT__unnamedblk2__DOT__ldir_y;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT__unnamedblk2__DOT__ldir_z;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT__unnamedblk2__DOT__ndotl;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT__unnamedblk2__DOT__dist_to_light;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT__unnamedblk2__DOT__shad_ox;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT__unnamedblk2__DOT__shad_oy;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT__unnamedblk2__DOT__shad_oz;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT__unnamedblk2__DOT__ndotn;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT__unnamedblk2__DOT__two_ndotn;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT__unnamedblk2__DOT__proj_x;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT__unnamedblk2__DOT__proj_y;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT__unnamedblk2__DOT__proj_z;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT__unnamedblk2__DOT__refl_raw_x;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT__unnamedblk2__DOT__refl_raw_y;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT__unnamedblk2__DOT__refl_raw_z;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT__unnamedblk2__DOT__eps_nx;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT__unnamedblk2__DOT__eps_ny;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT__unnamedblk2__DOT__eps_nz;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT__unnamedblk2__DOT__shade_r_i;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT__unnamedblk2__DOT__shade_g_i;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT__unnamedblk2__DOT__shade_b_i;
    };
    struct {
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT__unnamedblk2__DOT__rMix_i;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT__unnamedblk2__DOT__difQInt_i;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT__unnamedblk2__DOT__unnamedblk3__DOT__unnamedblk5__DOT__si2;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__normalize3_task__4__nx;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__normalize3_task__4__ny;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__normalize3_task__4__nz;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_sqrt_fn__6__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_sqrt_fn__6__result;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__7__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__7__a;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__7__b;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__7__quotient;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__8__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__8__a;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__8__b;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__8__quotient;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__9__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__9__a;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__9__b;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__9__quotient;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__10__ox;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__10__oy;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__10__oz;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__10__dx;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__10__dy;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__10__dz;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__10__cx;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__10__cy;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__10__cz;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__10__radius;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__10__t;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__10__lx;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__10__ly;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__10__lz;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__10__a;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__10__halfB;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__10__l2;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__10__r2;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__10__c;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__10__hb2;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__10__ac;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__10__disc;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__10__sqrtDisc;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__10__negHalfB;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__10__num0;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__10__num1;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__10__t0;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__10__t1;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__11__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__11__ax;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__11__ay;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__11__az;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__11__bx;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__11__by;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__11__bz;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__12__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__12__ax;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__12__ay;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__12__az;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__12__bx;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__12__by;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__12__bz;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__13__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__13__ax;
    };
    struct {
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__13__ay;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__13__az;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__13__bx;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__13__by;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__13__bz;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__14__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__14__a;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__14__b;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__15__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__15__a;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__15__b;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__16__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__16__a;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__16__b;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_sqrt_fn__17__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_sqrt_fn__17__a;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_sqrt_fn__17__result;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__18__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__18__a;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__18__b;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__18__quotient;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__19__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__19__a;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__19__b;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__19__quotient;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__20__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__20__a;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__20__b;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__21__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__21__a;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__21__b;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__22__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__22__a;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__22__b;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__normalize3_task__23__x;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__normalize3_task__23__y;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__normalize3_task__23__z;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__normalize3_task__23__nx;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__normalize3_task__23__ny;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__normalize3_task__23__nz;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__normalize3_task__23__mag2;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__normalize3_task__23__mag;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__24__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__24__ax;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__24__ay;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__24__az;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__24__bx;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__24__by;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__24__bz;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_sqrt_fn__25__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_sqrt_fn__25__a;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_sqrt_fn__25__result;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__26__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__26__a;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__26__b;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__26__quotient;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__27__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__27__a;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__27__b;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__27__quotient;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__28__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__28__a;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__28__b;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__28__quotient;
    };
    struct {
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_sqrt_fn__29__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_sqrt_fn__29__a;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_sqrt_fn__29__result;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__30__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__30__ax;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__30__ay;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__30__az;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__30__bx;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__30__by;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__30__bz;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__normalize3_task__31__x;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__normalize3_task__31__y;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__normalize3_task__31__z;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__normalize3_task__31__nx;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__normalize3_task__31__ny;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__normalize3_task__31__nz;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__normalize3_task__31__mag2;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__normalize3_task__31__mag;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__32__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__32__ax;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__32__ay;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__32__az;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__32__bx;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__32__by;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__32__bz;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_sqrt_fn__33__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_sqrt_fn__33__a;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_sqrt_fn__33__result;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__34__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__34__a;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__34__b;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__34__quotient;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__35__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__35__a;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__35__b;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__35__quotient;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__36__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__36__a;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__36__b;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__36__quotient;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__37__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__37__ax;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__37__ay;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__37__az;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__37__bx;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__37__by;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__37__bz;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__38__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__38__a;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__38__b;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__39__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__39__a;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__39__b;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__40__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__40__a;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__40__b;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__41__ox;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__41__oy;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__41__oz;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__41__dx;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__41__dy;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__41__dz;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__41__cx;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__41__cy;
    };
    struct {
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__41__cz;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__41__radius;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__41__t;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__41__lx;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__41__ly;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__41__lz;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__41__a;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__41__halfB;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__41__l2;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__41__r2;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__41__c;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__41__hb2;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__41__ac;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__41__disc;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__41__sqrtDisc;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__41__negHalfB;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__41__num0;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__41__num1;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__41__t0;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__ray_sphere_task__41__t1;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__42__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__42__ax;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__42__ay;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__42__az;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__42__bx;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__42__by;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__42__bz;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__43__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__43__ax;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__43__ay;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__43__az;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__43__bx;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__43__by;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__43__bz;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__44__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__44__ax;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__44__ay;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__44__az;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__44__bx;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__44__by;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__44__bz;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__45__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__45__a;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__45__b;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__46__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__46__a;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__46__b;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__47__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__47__a;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__47__b;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_sqrt_fn__48__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_sqrt_fn__48__a;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_sqrt_fn__48__result;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__49__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__49__a;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__49__b;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__49__quotient;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__50__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__50__a;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__50__b;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__50__quotient;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__51__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__51__a;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__51__b;
    };
    struct {
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__52__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__52__ax;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__52__ay;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__52__az;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__52__bx;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__52__by;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__52__bz;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__53__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__53__a;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__53__b;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__54__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__54__a;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__54__b;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__55__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__55__a;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__55__b;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__normalize3_task__56__x;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__normalize3_task__56__y;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__normalize3_task__56__z;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__normalize3_task__56__nx;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__normalize3_task__56__ny;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__normalize3_task__56__nz;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__normalize3_task__56__mag2;
        IData/*31:0*/ __Vtask_tbGenericVga__DOT__dut__DOT__normalize3_task__56__mag;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__57__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__57__ax;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__57__ay;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__57__az;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__57__bx;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__57__by;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__57__bz;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_sqrt_fn__58__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_sqrt_fn__58__a;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_sqrt_fn__58__result;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__59__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__59__a;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__59__b;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__59__quotient;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__60__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__60__a;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__60__b;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__60__quotient;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__61__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__61__a;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__61__b;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__61__quotient;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__62__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__62__a;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__62__b;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__63__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__63__a;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__63__b;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__64__Vfuncout;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__64__a;
        IData/*31:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__64__b;
        IData/*31:0*/ __VactIterCount;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_sqrt_fn__6__v;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_sqrt_fn__6__rem;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_sqrt_fn__6__r;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__7__dividend_shifted;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__8__dividend_shifted;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__9__dividend_shifted;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__11__px;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__11__py;
    };
    struct {
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__11__pz;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__12__px;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__12__py;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__12__pz;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__13__px;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__13__py;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__13__pz;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__14__full_prod;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__14__rounded;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__15__full_prod;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__15__rounded;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__16__full_prod;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__16__rounded;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_sqrt_fn__17__v;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_sqrt_fn__17__rem;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_sqrt_fn__17__r;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__18__dividend_shifted;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__19__dividend_shifted;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__20__full_prod;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__20__rounded;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__21__full_prod;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__21__rounded;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__22__full_prod;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__22__rounded;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__24__px;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__24__py;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__24__pz;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_sqrt_fn__25__v;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_sqrt_fn__25__rem;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_sqrt_fn__25__r;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__26__dividend_shifted;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__27__dividend_shifted;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__28__dividend_shifted;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_sqrt_fn__29__v;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_sqrt_fn__29__rem;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_sqrt_fn__29__r;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__30__px;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__30__py;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__30__pz;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__32__px;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__32__py;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__32__pz;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_sqrt_fn__33__v;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_sqrt_fn__33__rem;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_sqrt_fn__33__r;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__34__dividend_shifted;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__35__dividend_shifted;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__36__dividend_shifted;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__37__px;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__37__py;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__37__pz;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__38__full_prod;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__38__rounded;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__39__full_prod;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__39__rounded;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__40__full_prod;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__40__rounded;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__42__px;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__42__py;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__42__pz;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__43__px;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__43__py;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__43__pz;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__44__px;
    };
    struct {
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__44__py;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__44__pz;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__45__full_prod;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__45__rounded;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__46__full_prod;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__46__rounded;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__47__full_prod;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__47__rounded;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_sqrt_fn__48__v;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_sqrt_fn__48__rem;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_sqrt_fn__48__r;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__49__dividend_shifted;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__50__dividend_shifted;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__51__full_prod;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__51__rounded;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__52__px;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__52__py;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__52__pz;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__53__full_prod;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__53__rounded;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__54__full_prod;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__54__rounded;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__55__full_prod;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__55__rounded;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__57__px;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__57__py;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_dot3_fn__57__pz;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_sqrt_fn__58__v;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_sqrt_fn__58__rem;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_sqrt_fn__58__r;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__59__dividend_shifted;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__60__dividend_shifted;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_div_fn__61__dividend_shifted;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__62__full_prod;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__62__rounded;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__63__full_prod;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__63__rounded;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__64__full_prod;
        QData/*63:0*/ __Vfunc_tbGenericVga__DOT__dut__DOT__q16_mul_fn__64__rounded;
        VlUnpacked<IData/*31:0*/, 3> tbGenericVga__DOT__dut__DOT__cx_arr;
        VlUnpacked<IData/*31:0*/, 3> tbGenericVga__DOT__dut__DOT__cy_arr;
        VlUnpacked<IData/*31:0*/, 3> tbGenericVga__DOT__dut__DOT__cz_arr;
        VlUnpacked<IData/*31:0*/, 3> tbGenericVga__DOT__dut__DOT__radius_arr;
        VlUnpacked<CData/*7:0*/, 3> tbGenericVga__DOT__dut__DOT__colorR_arr;
        VlUnpacked<CData/*7:0*/, 3> tbGenericVga__DOT__dut__DOT__colorG_arr;
        VlUnpacked<CData/*7:0*/, 3> tbGenericVga__DOT__dut__DOT__colorB_arr;
        VlUnpacked<IData/*31:0*/, 3> tbGenericVga__DOT__dut__DOT__refl_arr;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<1> __VactTriggered;
    VlTriggerVec<1> __VnbaTriggered;

    // INTERNAL VARIABLES
    VtbGenericVga__Syms* const vlSymsp;

    // CONSTRUCTORS
    VtbGenericVga___024root(VtbGenericVga__Syms* symsp, const char* v__name);
    ~VtbGenericVga___024root();
    VL_UNCOPYABLE(VtbGenericVga___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
